version: '3'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "9009:9009"
      - "3000:3000"
    volumes:
      - ${PWD}/project:/home/node/app
    stdin_open: true
    tty: true
